# This is an example mods.toml file. It contains the data relating to the loading mods.
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Partonetrain/iafgear/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
logoFile="icon.png" #optional
credits="Thanks to SilentChaos for SilentGear, Alexthe666 for Ice and Fire" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

# Dependencies
[[dependencies.iafgear]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.iafgear]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.iafgear]]
modId="silentgear"
mandatory=true
versionRange="${silentgear_version}"
ordering="AFTER"
side="BOTH"

[[dependencies.iafgear]]
modId="iceandfire"
mandatory=true
versionRange="${iceandfire_version}"
ordering="AFTER"
side="BOTH"